name: UI CI & Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build & Push UI Image
    runs-on: ubuntu-latest
    env:
      VERSION_PREFIX: ${{ vars.VERSION_PREFIX }}
      DOCKER_REPO: ${{ vars.DOCKER_REPO }}
      IMAGE_NAME: ${{ vars.IMAGE_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Compute VERSION
        run: echo "VERSION=${VERSION_PREFIX}.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & tag image
        run: |
          docker build \
            -t $DOCKER_REPO/$IMAGE_NAME:latest \
            -t $DOCKER_REPO/$IMAGE_NAME:$VERSION \
            -f Dockerfile .

      - name: Push both tags
        run: |
          docker push $DOCKER_REPO/$IMAGE_NAME:$VERSION
          docker push $DOCKER_REPO/$IMAGE_NAME:latest
